{
 "title": "API",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   { "name": "endpoint", "query": { "query": "label_values(operation_id)" } },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(kubernetes_pod_name)"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "status", "query": { "query": "label_values(status)" } }
  ]
 },
 "panels": [
  {
   "title": "Requests By Response Status Code",
   "type": "timeseries",
   "description": "All requests processed per second, including bad requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status) (rate(aptos_api_response_status_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", status=~\"$status\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "description": "Request count by endpoint per $interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(aptos_api_requests_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", status=~\"$status\"}[$interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Endpoints Latency",
   "type": "timeseries",
   "description": "Aggregated endpoints latency per $interval, can be filtered by $endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(aptos_api_requests_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(aptos_api_requests_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[$interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(aptos_api_requests_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\"}[$interval])))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Server Internal Errors",
   "type": "timeseries",
   "description": "Server Internal Errors (response code 500) while processing requests, grouped by endpoints",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(aptos_api_requests_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=~\"$role\", kubernetes_pod_name=~\"$kubernetes_pod_name\", status=\"500\"}[$interval]))"
    }
   ]
  }
 ]
}