{
 "title": "DDoS",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   { "name": "network_id", "query": "label_values(network_id)" },
   { "name": "role_type", "query": "label_values(role_type)" },
   { "name": "owner", "query": "label_values(owner)" },
   { "name": "rpc_protocol", "label": "RPC Protocol", "query": "label_values(protocol_id)" },
   { "name": "AggInterval", "label": "Aggregation Interval", "query": "1m,5m,15m,30m,1h,3h,1d,7d" },
   { "name": "container", "query": "label_values(container)" }
  ]
 },
 "panels": [
  { "title": "Inbound Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inbound Connected Peers",
   "type": "graph",
   "description": "Total Inbound connected peers.  There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role_type, network_id) (aptos_connections{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", owner=~\"$owner\", direction=\"inbound\"})",
     "legendFormat": "{{owner}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Inbound Pending Connection Upgrades",
   "type": "graph",
   "description": "The rate of new inbound connections on the network interface",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role_type, network_id) (rate(aptos_network_pending_connection_upgrades{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", owner=~\"$owner\", direction=\"inbound\" }[$AggInterval]))",
     "legendFormat": "{{owner}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Blocked Inbound Connections Rate (Connection Limit)",
   "type": "graph",
   "description": "Rate of connections being blocked by connection limits",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_connections_rejected{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", owner=~\"$owner\", direction=\"inbound\"}[1m])",
     "legendFormat": "{{owner}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Throughput of Total Inbound RPCs (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Inbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role_type, network_id)(rate(aptos_network_rpc_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", owner=~\"$owner\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{owner}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Rate of Total Inbound RPCs (msg/s)",
   "type": "graph",
   "description": "Total number of all Inbound RPC requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role_type, network_id)(rate(aptos_network_rpc_messages{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", owner=~\"$owner\", type=\"request\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{owner}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Throughput of Total Inbound Direct Sends (bytes/s)",
   "type": "graph",
   "description": "Total throughput of all Inbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role_type, network_id)(rate(aptos_network_direct_send_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", owner=~\"$owner\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{owner}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "Rate of Total Inbound Direct Sends (msg/s)",
   "type": "graph",
   "description": "Total number of all Inbound Direct Send requests per peer",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, role_type, network_id)(rate(aptos_network_direct_send_messages{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=~\"$network_id\", role_type=~\"$role_type\", owner=~\"$owner\", state=\"received\"}[$AggInterval]))",
     "legendFormat": "{{owner}}-{{role_type}}-{{network_id}}"
    }
   ]
  },
  {
   "title": "VFN Public Inbound Allowed bytes (bytes/s)",
   "type": "graph",
   "description": "number of bytes allowed through the throttler inbound per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_rate_limit_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", metric=\"allowed\", direction=\"inbound\", owner=~\"$owner\"}[$AggInterval])",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "VFN Public Inbound Rate Limiting (bytes/s)",
   "type": "graph",
   "description": "number of bytes throttled inbound per second including partial messages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "bytes/s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_network_rate_limit_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", metric=\"throttled\", direction=\"inbound\", owner=~\"$owner\"}[$AggInterval])",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Usage - $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "repeat": "container",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (owner, container) (rate(container_cpu_usage_seconds_total{container=~\"$container\", owner=~\"$owner\"}[$AggInterval]))",
     "legendFormat": "{{owner}}-{{container}}"
    },
    {
     "expr": "sum by (owner, container_name) (rate(container_cpu_usage_seconds_total{container_name=~\"$container\", owner=~\"$owner\"}[$AggInterval]))",
     "legendFormat": "{{owner}}-{{container_name}}"
    }
   ]
  },
  {
   "title": "IO Operations - $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "repeat": "container",
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{container=~\"$container\", owner=~\"$owner\"}[$AggInterval])",
     "legendFormat": "{{owner}}-{{container}}-reads"
    },
    {
     "expr": "rate(container_fs_writes_total{container=~\"$container\", owner=~\"$owner\"}[$AggInterval])",
     "legendFormat": "{{owner}}-{{container}}-writes"
    },
    {
     "expr": "rate(container_fs_reads_total{container_name=~\"$container\", owner=~\"$owner\"}[$AggInterval]) ",
     "legendFormat": "{{owner}}-{{container_name}}-reads"
    },
    {
     "expr": "rate(container_fs_writes_total{container_name=~\"$container\", owner=~\"$owner\"}[$AggInterval])",
     "legendFormat": "{{owner}}-{{container_name}}-writes"
    }
   ]
  },
  {
   "title": "Memory Usage % - $container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "repeat": "container",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=~\"$container\", owner=~\"$owner\"} / container_spec_memory_limit_bytes{container=~\"$container\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{container}}"
    },
    {
     "expr": "container_memory_working_set_bytes{container_name=~\"$container\", owner=~\"$owner\"} / container_spec_memory_limit_bytes{container_name=~\"$container\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{container_name}}"
    }
   ]
  },
  {
   "title": "Disk Usage % -$container",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "repeat": "container",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*-($container)-e.*\", owner=~\"$owner\"} / kubelet_volume_stats_capacity_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*-($container)-e.*\", owner=~\"$owner\"}",
     "legendFormat": "{{owner}}-{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}