{
 "title": "Diversity",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Region Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(count by (failure_domain_beta_kubernetes_io_region\n) (count by (kubernetes_pod_name, failure_domain_beta_kubernetes_io_region\n) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\"}))) / ignoring(failure_domain_beta_kubernetes_io_region) group_left count(count by (kubernetes_pod_name, failure_domain_beta_kubernetes_io_region\n) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\"}))",
     "legendFormat": "{{failure_domain_beta_kubernetes_io_region}}"
    }
   ]
  },
  {
   "title": "Cloud Distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"ip.*\"})) / (count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"ip.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"aks.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"gke.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"scw.*\"})))",
     "legendFormat": "AWS"
    },
    {
     "expr": "count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"aks.*\"})) / (count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"ip.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"aks.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"gke.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"scw.*\"})))",
     "legendFormat": "Azure"
    },
    {
     "expr": "count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"gke.*\"})) / (count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"ip.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"aks.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"gke.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"scw.*\"})))",
     "legendFormat": "GCP"
    },
    {
     "expr": "count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"scw.*\"})) / (count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"ip.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"aks.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"gke.*\"})) + count(count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"scw.*\"})))",
     "legendFormat": "Scaleway"
    }
   ]
  },
  {
   "title": "Server Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (beta_kubernetes_io_instance_type\n) (count by (kubernetes_pod_name, beta_kubernetes_io_instance_type\n) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\"}))",
     "legendFormat": "{{beta_kubernetes_io_instance_type}}"
    }
   ]
  },
  {
   "title": "Region<>Node Mapping",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (kubernetes_pod_name, failure_domain_beta_kubernetes_io_region\n) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\"})",
     "legendFormat": "{{kubernetes_pod_name}}-{{failure_domain_beta_kubernetes_io_region}}"
    }
   ]
  },
  {
   "title": "Cloud<>Node Mapping",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"ip.*\"})",
     "legendFormat": "{{kubernetes_pod_name}}-AWS"
    },
    {
     "expr": "count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"aks.*\"})",
     "legendFormat": "{{kubernetes_pod_name}}-Azure"
    },
    {
     "expr": "count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"gke.*\"})",
     "legendFormat": "{{kubernetes_pod_name}}-GCP"
    },
    {
     "expr": "count by (kubernetes_pod_name) (kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", instance=~\"scw.*\"})",
     "legendFormat": "{{kubernetes_pod_name}}-Scaleway"
    }
   ]
  },
  {
   "title": "Kubernetes Node Versions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kubernetes_build_info{chain_name=~\"$chain_name\", namespace=~\"$namespace\"}) by (kubernetes_pod_name, git_version)",
     "legendFormat": "{{kubernetes_pod_name}}-{{git_version}}"
    }
   ]
  }
 ]
}