{
 "title": "Execution",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   {
    "name": "kubernetes_pod_name",
    "query": "label_values(kubernetes_pod_name)"
   },
   { "name": "role", "query": "label_values(role)" },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Percentiles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block execution time [p50]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_execute_block_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block execution time [p90]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_execute_block_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Block execution time [p99]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_execute_block_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Time spent in storage to save transactions [p50]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent for persisting execution result to storage when committing blocks",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_save_transactions_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role,le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Time spent in storage to save transactions [p90]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent for persisting execution result to storage when committing blocks",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_save_transactions_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role,le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Time spent in storage to save transactions [p99]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent for persisting execution result to storage when committing blocks",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_save_transactions_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role,le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "VM execute block time [p50]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block in VM",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_vm_execute_block_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "VM execute block time [p90]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block in VM",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_vm_execute_block_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "VM execute block time [p99]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to execute a block in VM",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_vm_execute_block_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks [p50]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(aptos_executor_commit_blocks_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks [p90]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(aptos_executor_commit_blocks_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Total time to commit blocks [p99]",
   "type": "graph",
   "description": "p50, p95 and p99 of the time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(aptos_executor_commit_blocks_seconds_bucket{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])) by (kubernetes_pod_name, role, le))",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  { "title": "Validators", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Avg Block execution time",
   "type": "graph",
   "description": "The average time spent to execute a block",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_execute_block_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_executor_execute_block_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg  VM execute block time",
   "type": "graph",
   "description": "The average time spent to execute a block in VM",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_vm_execute_block_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_executor_vm_execute_block_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg  Total time to commit blocks",
   "type": "graph",
   "description": "The average time spent to commit blocks",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_commit_blocks_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_executor_commit_blocks_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg  Time spent in storage to save transactions",
   "type": "graph",
   "description": "The average time spent for persisting execution result to storage when committing blocks",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_save_transactions_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_executor_save_transactions_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Avg Execute and commit chunk time",
   "type": "graph",
   "description": "The average time spent for executing and committing each chunk in state-syncing",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(aptos_executor_execute_and_commit_chunk_seconds_sum{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval]) / rate(aptos_executor_execute_and_commit_chunk_seconds_count{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "Executor Error Counter",
   "type": "graph",
   "description": "The counter that indicates the number of errors reported.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aptos_executor_error_total{chain_name=~\"$chain_name\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  }
 ]
}