{
 "title": "System",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   { "name": "container", "query": { "query": "label_values(container)" } },
   { "name": "pod", "query": { "query": "label_values(pod)" } },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{chain_name=~\"$chain_name\", namespace=~\"$namespace\", container=~\"$container\"}[$interval])",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", container=~\"$container\"}",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", container=~\"$container\"} / container_spec_memory_limit_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", container=~\"$container\"}",
     "legendFormat": "{{pod}}-{{container}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*-($container)-e.*\"} / kubelet_volume_stats_capacity_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*-($container)-e.*\"}",
     "legendFormat": "{{pod}}-{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{chain_name=~\"$chain_name\", namespace=~\"$namespace\", persistentvolumeclaim=~\".*($container)-e.*\"}",
     "legendFormat": "{{pod}}-{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{chain_name=~\"$chain_name\", namespace=~\"$namespace\", pod=~\".+$container(-e[0-9]+)?-0\"}[$interval]) + rate(container_network_transmit_bytes_total{chain_name=~\"$chain_name\", namespace=~\"$namespace\", pod=~\".+$container(-e[0-9]+)?-0\"}[$interval])",
     "legendFormat": "{{pod}}-{{pod}}"
    },
    {
     "expr": "rate(container_network_receive_bytes_total{chain_name=~\"$chain_name\", namespace=~\"$namespace\", pod_name=~\".+$container(-e[0-9]+)?-0\"}[$interval]) + rate(container_network_transmit_bytes_total{chain_name=~\"$chain_name\", namespace=~\"$namespace\", pod_name=~\".+$container(-e[0-9]+)?-0\"}[$interval])",
     "legendFormat": "{{pod}}-{{pod_name}}"
    }
   ]
  },
  {
   "title": "IO Operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_total{chain_name=~\"$chain_name\", namespace=~\"$namespace\", container=~\"$container\"}[$interval]) + rate(container_fs_writes_total{chain_name=~\"$chain_name\", namespace=~\"$namespace\", container=~\"$container\"}[$interval])",
     "legendFormat": "{{pod}}-{{pod}}:{{container}}:{{device}}"
    }
   ]
  }
 ]
}