{
 "title": "Validator Connectivity",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "chain_name", "query": { "query": "label_values(chain_name)" } },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(aptos_network_peer_connected, kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ValidatorSet",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "quantile(0.67, aptos_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Down node %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - (count(rate(aptos_consensus_current_round[10m]) > 0) OR on() vector(0)) / quantile(0.67, aptos_consensus_current_epoch_validators)"
    }
   ]
  },
  {
   "title": "Not reporting metrics",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "up{chain_name=~\"$chain_name\", namespace=~\"$namespace\", job=\"federate\"} == 0 or up{chain_name=~\"$chain_name\", namespace=~\"$namespace\", job=\"aptos-procs\", role=\"validator\"} == 0"
    }
   ]
  },
  {
   "title": "Node not Participating Consensus",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_current_round{chain_name=~\"$chain_name\", namespace=~\"$namespace\", role=\"validator\"}[1m]) == 0"
    }
   ]
  },
  { "title": "Connected Peers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Total Connected Peers",
   "type": "graph",
   "description": "Total Connected Peers for both inbound and outbound per peer.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id) (aptos_connections{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=\"Validator\", role_type=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\"})\n",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Inbound Connected Peers",
   "type": "graph",
   "description": "Total Inbound connected peers. There should be at most one peer with 0 inbound connections.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id) (aptos_connections{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=\"Validator\", role_type=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", direction=\"inbound\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Outbound Connected Peers",
   "type": "graph",
   "description": "Total outbound connections per peer. Every node should have an outbound connection.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name, role_type, network_id)(aptos_connections{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=\"Validator\", role_type=\"validator\", kubernetes_pod_name=~\"$kubernetes_pod_name\", direction=\"outbound\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Connectivity Matrix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Current Validator Connections",
   "type": "table",
   "description": "An adjacency matrix showing each (validator -> remote validator) connection. Each row shows the \"kubernetes_pod_name\" node's view of its own connections to each other validator.\n\nA green \"1\" means there is currently a connection, while a red \"0\" means the nodes are not currently connected. An empty square means there is no reported metric for this (kubernetes_pod_name_i, kubernetes_pod_name_j) pair, which is expected for (kubernetes_pod_name_i, kubernetes_pod_name_i) since we don't allow self-connections.",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "# Filter out extraneous fields.\nsum by (kubernetes_pod_name, remote_kubernetes_pod_name) (\n  (\n    aptos_network_peer_connected{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=\"Validator\", role_type=\"validator\"}\n\n  # Do a left join on a table containing labels [\"remote_peer_id\", \"remote_kubernetes_pod_name\"]\n  # to join in \"remote_kubernetes_pod_name\" for each \"remote_peer_id\".\n  ) + on(remote_peer_id) group_left(remote_kubernetes_pod_name) (\n\n    # We can only left join with certain bin-ops, so we force all values to zero\n    # here so we can add without messing up the connection values.\n    clamp_max(\n      # Filter out extraneous fields.\n      sum by (remote_kubernetes_pod_name, remote_peer_id) (\n        sum without (direction) (\n          # Rename \"peer_id\" -> \"remote_peer_id\" and \"kubernetes_pod_name\" -> \"remote_kubernetes_pod_name\" so\n          # these fields don't conflict with those from peer_connected.\n          label_replace(\n            label_replace(\n              aptos_connections{chain_name=~\"$chain_name\", namespace=~\"$namespace\", network_id=\"Validator\", role_type=\"validator\"},\n              \"remote_peer_id\", \"$1\",\n              \"peer_id\", \"(.*)\"\n            ),\n            \"remote_kubernetes_pod_name\", \"$1\",\n            \"kubernetes_pod_name\", \"(.*)\"\n          )\n        )\n      ),\n      0\n    )\n  )\n)"
    }
   ]
  }
 ]
}